basic:
    name: 'test project'
    environments:
        production: 'https://cuttingboards.com/'
        staging: 'https://cuttingboarstg.wpenginepowered.com/'
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /
        - cutting-boards
        - interlocking-boards
        - made-to-order
        - custom-made
        - pizza-boards
        - bread-boards
        - cook-tools
        - company
        - careers
        - contact
        - lifetime-guarantee
        - terms-and-conditions
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
